import { useOutletContext } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import PageHeader from "../components/PageHeader.jsx";
import PanelSection from "../components/PanelSection.jsx";
import DataTable from "../components/DataTable.jsx";
import StudentProfileModal from "../components/StudentProfileModal.jsx";
import { useAuth, useAccessProfile } from "../contexts/AuthContext.jsx";
import { canUseInternshipsApi, listInternships } from "../services/internshipsService.js";
import { listProfilesByType } from "../services/profilesService.js";
import { adminListUsers } from "../services/usersAdminService.js";

const STORAGE_KEY = "giva.internships.filters";
const PAGE_SIZE_OPTIONS = [3, 5, 10];
const ALLOWED_STATUS = new Set(["active", "monitoring", "risk"]);

function toSafeText(value) {
  return String(value ?? "")
    .replace(/[\u0000-\u001F\u007F]/g, "")
    .replace(/[<>]/g, "")
    .trim();
}

function toSafeImageUrl(value) {
  const raw = toSafeText(value);
  if (!raw) {
    return "";
  }

  // data: URIs from bundled assets (Vite) — already trusted at build time
  if (raw.startsWith("data:image/")) {
    return raw;
  }

  // Relative asset path generated by Vite — safe by construction
  if (raw.startsWith("/")) {
    return raw;
  }

  // Remote URLs — encode to prevent injection via specially crafted values
  if (raw.startsWith("https://") || raw.startsWith("http://")) {
    return encodeURI(raw);
  }

  return "";
}

function normalizeInternshipRow(row) {
  const status = toSafeText(row?.status);

  return {
    ...row,
    id: row?.id,
    processo: toSafeText(row?.processo),
    aluno: toSafeText(row?.aluno),
    turma: toSafeText(row?.turma),
    anoLetivo: toSafeText(row?.anoLetivo),
    curso: toSafeText(row?.curso),
    empresa: toSafeText(row?.empresa),
    supervisor: toSafeText(row?.supervisor),
    inicio: toSafeText(row?.inicio),
    ultimaAtualizacao: toSafeText(row?.ultimaAtualizacao),
    nota: String(Number(row?.nota ?? 0)),
    status: ALLOWED_STATUS.has(status) ? status : "active",
    photo: toSafeImageUrl(row?.photo),
  };
}

function toCurrentAcademicYearLabel() {
  const year = new Date().getFullYear();
  return `${year}/${year + 1}`;
}

function buildPlaceholderStudentRow(profile) {
  const studentAccount = Array.isArray(profile?.student_accounts)
    ? profile.student_accounts[0]
    : profile?.student_accounts;

  return {
    id: `profile-${profile.id}`,
    processo: studentAccount?.process_number ?? "",
    aluno: profile?.display_name ?? "Aluno sem nome",
    turma: "Sem turma",
    anoLetivo: toCurrentAcademicYearLabel(),
    curso: studentAccount?.course ?? "Sem curso",
    empresa: "Sem empresa",
    supervisor: "—",
    inicio: "—",
    ultimaAtualizacao: "—",
    nota: "0",
    status: "monitoring",
    photo: profile?.avatar_url ?? "",
    email: "",
    telefone: "",
  };
}

function mergeWithStudentsWithoutInternship(internshipRows, studentProfiles) {
  const normalizedInternships = internshipRows.map(normalizeInternshipRow);

  const existingByProcess = new Set(
    normalizedInternships
      .map((item) => toSafeText(item.processo).toLowerCase())
      .filter(Boolean)
  );

  const existingByName = new Set(
    normalizedInternships
      .map((item) => toSafeText(item.aluno).toLowerCase())
      .filter(Boolean)
  );

  const placeholders = (studentProfiles ?? [])
    .map(buildPlaceholderStudentRow)
    .map(normalizeInternshipRow)
    .filter((row) => {
      const processKey = toSafeText(row.processo).toLowerCase();
      const nameKey = toSafeText(row.aluno).toLowerCase();

      if (processKey && existingByProcess.has(processKey)) return false;
      if (nameKey && existingByName.has(nameKey)) return false;
      return true;
    });

  return [...normalizedInternships, ...placeholders];
}

function mapAdminUsersToStudentProfiles(users) {
  return (users ?? [])
    .filter((user) => user?.type === "student")
    .map((user) => ({
      id: user.id,
      display_name: user.display_name,
      avatar_url: user.avatar_url,
      type: user.type,
      student_accounts: null,
    }));
}

function readStoredFilters() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      return null;
    }
    const parsed = JSON.parse(raw);
    const pageSize = PAGE_SIZE_OPTIONS.includes(parsed.pageSize) ? parsed.pageSize : 3;
    return {
      statusFilter: typeof parsed.statusFilter === "string" ? parsed.statusFilter : "all",
      schoolYearFilter: typeof parsed.schoolYearFilter === "string" ? parsed.schoolYearFilter : "all",
      classFilter: typeof parsed.classFilter === "string" ? parsed.classFilter : "all",
      classSortBy: parsed.classSortBy === "date" || parsed.classSortBy === "name" ? parsed.classSortBy : "grade",
      pageSize,
    };
  } catch {
    return null;
  }
}

function statusLabel(status, copy) {
  if (status === "active") return copy.active;
  if (status === "monitoring") return copy.monitoring;
  return copy.risk;
}

function initials(name) {
  return String(name ?? "")
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}

function parseDateLabel(value) {
  if (!value) {
    return 0;
  }
  const parts = value.split(" ");
  if (parts.length !== 3) {
    return 0;
  }
  const day = Number(parts[0]);
  const monthMap = {
    Jan: 0,
    Fev: 1,
    Mar: 2,
    Abr: 3,
    Mai: 4,
    Jun: 5,
    Jul: 6,
    Ago: 7,
    Set: 8,
    Out: 9,
    Nov: 10,
    Dez: 11,
  };
  const month = monthMap[parts[1]];
  const year = Number(parts[2]);
  if (Number.isNaN(day) || Number.isNaN(year) || month === undefined) {
    return 0;
  }
  return new Date(year, month, day).getTime();
}

export default function InternshipsPage() {
  const { showToast, t } = useOutletContext();
  const { user, userProfile, loading: authLoading } = useAuth();
  const { isAdmin: isAdminView, isStudentUser: isStudentView, isCompanyUser: isCompanyView } = useAccessProfile();
  const savedFilters = useMemo(() => readStoredFilters(), []);
  const [selectedStudent, setSelectedStudent] = useState(null);
  const copy = {
    active: t("internships.active"),
    monitoring: t("internships.monitoring"),
    risk: t("internships.risk")
  };
  const [statusFilter, setStatusFilter] = useState(savedFilters?.statusFilter ?? "all");
  const [schoolYearFilter, setSchoolYearFilter] = useState(savedFilters?.schoolYearFilter ?? "all");
  const [classFilter, setClassFilter] = useState(savedFilters?.classFilter ?? "all");
  const [classSortBy, setClassSortBy] = useState(savedFilters?.classSortBy ?? "grade");
  const [pageSize, setPageSize] = useState(savedFilters?.pageSize ?? 3);
  const [classPage, setClassPage] = useState({});
  const [rows, setRows] = useState([]);
  const [loadingRows, setLoadingRows] = useState(true);

  useEffect(() => {
    let active = true;

    if (authLoading) {
      return () => {
        active = false;
      };
    }

    async function loadRows() {
      if (active) {
        setLoadingRows(true);
      }

      if (!canUseInternshipsApi()) {
        if (active) {
          setRows([]);
          setLoadingRows(false);
        }
        return;
      }

      // Perfil ainda não disponível: evita expor lista ampla para aluno/empresa antes do scoping.
      if (!isAdminView && !userProfile) {
        if (active) {
          setRows([]);
          setLoadingRows(false);
        }
        return;
      }

      try {
        const [internshipsResult, studentsResult] = await Promise.allSettled([
          listInternships(),
          isAdminView ? listProfilesByType("student") : Promise.resolve([]),
        ]);

        const remoteRows = internshipsResult.status === "fulfilled"
          ? internshipsResult.value.map(normalizeInternshipRow)
          : [];
        let studentProfiles = studentsResult.status === "fulfilled" ? studentsResult.value : [];

        if (isAdminView && studentProfiles.length === 0) {
          try {
            const adminUsers = await adminListUsers();
            const adminStudents = mapAdminUsersToStudentProfiles(adminUsers);
            if (adminStudents.length > 0) {
              studentProfiles = adminStudents;
            }
          } catch {
            // noop: fallback admin disponível apenas para perfis administrativos
          }
        }

        if (!active) {
          return;
        }

        let scopedRows = remoteRows;

        if (isStudentView) {
          const profileName = toSafeText(userProfile?.display_name).toLowerCase();
          const processNumber = toSafeText(userProfile?.student_accounts?.process_number).toLowerCase();

          scopedRows = remoteRows.filter((row) => {
            const rowName = toSafeText(row.aluno).toLowerCase();
            const rowProcess = toSafeText(row.processo).toLowerCase();
            if (processNumber && rowProcess && rowProcess === processNumber) {
              return true;
            }
            return profileName && rowName === profileName;
          });

          if (scopedRows.length === 0 && userProfile) {
            scopedRows = [normalizeInternshipRow(buildPlaceholderStudentRow(userProfile))];
          }
        } else if (isCompanyView) {
          const companyName = toSafeText(
            userProfile?.company_accounts?.empresa ?? userProfile?.display_name
          ).toLowerCase();

          scopedRows = remoteRows.filter(
            (row) => companyName && toSafeText(row.empresa).toLowerCase() === companyName
          );
        } else if (isAdminView) {
          scopedRows = mergeWithStudentsWithoutInternship(remoteRows, studentProfiles);
        }

        setRows(scopedRows);

        if (internshipsResult.status === "rejected" && isAdminView && studentProfiles.length > 0) {
          showToast("Falha ao carregar estágios remotos. A exibir alunos sem estágio/turma.", "warning");
        }

        if (internshipsResult.status === "rejected" && studentsResult.status === "rejected") {
          showToast("Falha ao carregar estágios na base remota.", "error");
        }
      } catch {
        if (active) {
          setRows([]);
          showToast("Falha ao carregar estagios na base remota.", "error");
        }
      } finally {
        if (active) {
          setLoadingRows(false);
        }
      }
    }

    loadRows();

    return () => {
      active = false;
    };
  }, [authLoading, isAdminView, isCompanyView, isStudentView, user?.id]);

  useEffect(() => {
    localStorage.setItem(
      STORAGE_KEY,
      JSON.stringify({
        statusFilter,
        schoolYearFilter,
        classFilter,
        classSortBy,
        pageSize,
      })
    );
  }, [classFilter, classSortBy, pageSize, schoolYearFilter, statusFilter]);

  useEffect(() => {
    setClassPage({});
  }, [classFilter, classSortBy, pageSize, schoolYearFilter, statusFilter]);

  const schoolYearOptions = useMemo(
    () => [...new Set(rows.map((row) => row.anoLetivo))].sort((a, b) => b.localeCompare(a)),
    [rows]
  );

  const classOptions = useMemo(
    () => [...new Set(rows.map((row) => row.turma))].sort((a, b) => a.localeCompare(b)),
    [rows]
  );

  const filtered = useMemo(
    () =>
      rows.filter((row) => {
        const statusOk = statusFilter === "all" || row.status === statusFilter;
        const yearOk = schoolYearFilter === "all" || row.anoLetivo === schoolYearFilter;
        const classOk = classFilter === "all" || row.turma === classFilter;
        const textOk = true;
        return statusOk && yearOk && classOk && textOk;
      }),
    [classFilter, rows, schoolYearFilter, statusFilter]
  );

  const classGroups = useMemo(() => {
    const map = new Map();
    for (const row of filtered) {
      const key = `${row.anoLetivo}|${row.turma}`;
      if (!map.has(key)) {
        map.set(key, {
          turma: row.turma,
          anoLetivo: row.anoLetivo,
          curso: row.curso,
          supervisor: row.supervisor,
          alunos: [],
        });
      }
      map.get(key).alunos.push(row);
    }

    for (const group of map.values()) {
      group.alunos.sort((a, b) => {
        if (classSortBy === "name") {
          return a.aluno.localeCompare(b.aluno);
        }

        if (classSortBy === "date") {
          const dateDiff = parseDateLabel(b.ultimaAtualizacao) - parseDateLabel(a.ultimaAtualizacao);
          if (dateDiff !== 0) {
            return dateDiff;
          }
          return Number(b.nota) - Number(a.nota);
        }

        const gradeDiff = Number(b.nota) - Number(a.nota);
        if (gradeDiff !== 0) {
          return gradeDiff;
        }
        return parseDateLabel(b.ultimaAtualizacao) - parseDateLabel(a.ultimaAtualizacao);
      });
    }

    return Array.from(map.values()).sort((a, b) => {
      if (a.anoLetivo === b.anoLetivo) {
        return a.turma.localeCompare(b.turma);
      }
      return b.anoLetivo.localeCompare(a.anoLetivo);
    });
  }, [classSortBy, filtered]);

  const columns = [
    {
      key: "aluno",
      label: t("common.student"),
      render: (row) => (
        <button type="button" className="btn-student-name" onClick={() => setSelectedStudent(row)}>
          <img className="student-avatar-sm" src={row.photo} alt="" />
          {row.aluno}
        </button>
      ),
    },
    { key: "turma", label: t("internships.class") },
    { key: "anoLetivo", label: t("internships.schoolYear") },
    { key: "curso", label: t("common.course") },
    { key: "empresa", label: t("common.company") },
    { key: "inicio", label: t("internships.startDate") },
    { key: "nota", label: t("internships.internshipGrade") },
    { key: "status", label: t("common.status"), render: (row) => statusLabel(row.status, copy) },
    {
      key: "acao",
      label: t("common.action"),
      render: (row) => (
        <button
          className="btn ghost"
          type="button"
          onClick={() => showToast(t("internships.toast.details").replace("{name}", toSafeText(row.aluno)))}
        >
          {t("common.details")}
        </button>
      )
    }
  ];

  return (
    <main className="page page-internships">
      <PageHeader
        title={t("internships.title")}
        description={t("internships.description")}
        meta={
          <div className="internships-toolbar">
            <span className="tag">
              <span className="material-icons-sharp">filter_alt</span>
              {t("internships.filter")}
              <select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}>
                <option value="all">{t("internships.all")}</option>
                <option value="active">{t("internships.active")}</option>
                <option value="monitoring">{t("internships.monitoring")}</option>
                <option value="risk">{t("internships.risk")}</option>
              </select>
            </span>

            <span className="tag">
              <span className="material-icons-sharp">calendar_month</span>
              {t("internships.schoolYear")}
              <select value={schoolYearFilter} onChange={(event) => setSchoolYearFilter(event.target.value)}>
                <option value="all">{t("internships.allYears")}</option>
                {schoolYearOptions.map((year) => (
                  <option key={year} value={year}>{year}</option>
                ))}
              </select>
            </span>

            <span className="tag">
              <span className="material-icons-sharp">groups</span>
              {t("internships.class")}
              <select value={classFilter} onChange={(event) => setClassFilter(event.target.value)}>
                <option value="all">{t("internships.allClasses")}</option>
                {classOptions.map((className) => (
                  <option key={className} value={className}>{className}</option>
                ))}
              </select>
            </span>
          </div>
        }
      />

      <PanelSection title={t("internships.priorityList")}>
        {loadingRows ? (
          <p className="meta loading-state">{t("internships.loading")}</p>
        ) : (
          <DataTable columns={columns} rows={filtered} />
        )}
      </PanelSection>

      <PanelSection title={t("internships.classListTitle")}>
        <div className="internships-class-controls">
          <span className="tag">
            <span className="material-icons-sharp">sort</span>
            {t("internships.sortBy")}
            <select value={classSortBy} onChange={(event) => setClassSortBy(event.target.value)}>
              <option value="grade">{t("internships.sortGrade")}</option>
              <option value="date">{t("internships.sortDate")}</option>
              <option value="name">{t("internships.sortName")}</option>
            </select>
          </span>

          <span className="tag">
            <span className="material-icons-sharp">format_list_numbered</span>
            {t("internships.itemsPerPage")}
            <select value={pageSize} onChange={(event) => setPageSize(Number(event.target.value))}>
              {PAGE_SIZE_OPTIONS.map((size) => (
                <option key={size} value={size}>{size}</option>
              ))}
            </select>
          </span>
        </div>

        <div className="class-grid">
          {loadingRows ? (
            <p className="meta loading-state">{t("internships.loading")}</p>
          ) : classGroups.length ? (
            classGroups.map((group) => {
              const groupKey = `${group.anoLetivo}-${group.turma}`;
              const totalPages = Math.max(1, Math.ceil(group.alunos.length / pageSize));
              const currentPage = Math.min(classPage[groupKey] ?? 1, totalPages);
              const startIndex = (currentPage - 1) * pageSize;
              const visibleStudents = group.alunos.slice(startIndex, startIndex + pageSize);

              return (
                <article className="class-card" key={groupKey}>
                <header className="class-card-head">
                  <div>
                    <h4>{group.turma}</h4>
                    <p>
                      {t("internships.schoolYear")}: {group.anoLetivo}
                    </p>
                    <p>
                      {t("common.course")}: {group.curso}
                    </p>
                  </div>
                  <span className="tag">{group.alunos.length} {t("internships.studentsCount")}</span>
                </header>

                <div className="class-list">
                  {visibleStudents.map((student) => (
                    <button
                      className="class-list-item"
                      key={student.id}
                      type="button"
                      onClick={() => setSelectedStudent(student)}
                    >
                      <span className="student-avatar-md" aria-hidden="true">{initials(student.aluno)}</span>

                      <div className="class-list-copy">
                        <strong>{student.aluno}</strong>
                        <small>
                          {t("internships.startDate")}: {student.inicio} • {t("internships.internshipGrade")}: {student.nota}
                        </small>
                        <small>
                          {t("internships.lastUpdate")}: {student.ultimaAtualizacao}
                        </small>
                      </div>

                      <span className="tag class-list-tag">{statusLabel(student.status, copy)}</span>
                    </button>
                  ))}
                </div>

                {totalPages > 1 ? (
                  <div className="class-pagination" role="navigation" aria-label={t("internships.paginationLabel")}>
                    <button
                      className="btn ghost"
                      type="button"
                      onClick={() =>
                        setClassPage((current) => ({
                          ...current,
                          [groupKey]: Math.max(1, (current[groupKey] ?? 1) - 1),
                        }))
                      }
                      disabled={currentPage === 1}
                    >
                      {t("internships.previous")}
                    </button>

                    <span className="meta">
                      {t("internships.page")}: {currentPage}/{totalPages}
                    </span>

                    <button
                      className="btn ghost"
                      type="button"
                      onClick={() =>
                        setClassPage((current) => ({
                          ...current,
                          [groupKey]: Math.min(totalPages, (current[groupKey] ?? 1) + 1),
                        }))
                      }
                      disabled={currentPage === totalPages}
                    >
                      {t("internships.next")}
                    </button>
                  </div>
                ) : null}

                <footer className="class-card-foot">
                  {t("internships.supervisor")}: {group.supervisor}
                </footer>
                </article>
              );
            })
          ) : (
            <p className="meta">{t("internships.emptyClasses")}</p>
          )}
        </div>
      </PanelSection>

      {selectedStudent !== null && (
        <StudentProfileModal
          student={selectedStudent}
          onClose={() => setSelectedStudent(null)}
          t={t}
        />
      )}
    </main>
  );
}
